import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isBuiltin } from 'node:module';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv[2] === '--check';
if (process.argv.length > 3 || (process.argv[2] && !check)) {
  throw new Error('Usage: node scripts/build-runner.js [--check]');
}

const result = await build({
  absWorkingDir: root,
  entryPoints: ['bin/stellar.js'],
  outfile: 'bin/stellar.mjs',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  write: false,
  metafile: true,
  legalComments: 'inline',
  banner: {
    js: '// Generated by just build-runner. Edit bin/stellar.js and lib/, then regenerate.\n// Dependency license texts: ../THIRD_PARTY_NOTICES.txt',
  },
});

for (const output of Object.values(result.metafile.outputs)) {
  for (const dependency of output.imports) {
    if (dependency.external && !isBuiltin(dependency.path)) {
      throw new Error(
        `Installed runner has an external package: ${dependency.path}`,
      );
    }
  }
}

// Include the full license of every dependency that actually enters the bundle.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!('/' + input).includes('/node_modules/')) continue;
  let at = dirname(resolve(root, input));
  while (at !== root) {
    let pkg;
    try {
      pkg = JSON.parse(await readFile(join(at, 'package.json'), 'utf8'));
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
      at = dirname(at);
      continue;
    }
    const identity = `${pkg.name}@${pkg.version}`;
    if (!packages.has(identity)) {
      let license;
      for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license']) {
        try {
          license = await readFile(join(at, name), 'utf8');
          break;
        } catch (error) {
          if (error.code !== 'ENOENT') throw error;
        }
      }
      if (!license) throw new Error(`Missing license for ${pkg.name}`);
      packages.set(
        identity,
        `${identity} (${pkg.license})\n\n${license.trim()}\n`,
      );
    }
    break;
  }
}
const notices =
  'Third-party software included in bin/stellar.mjs\nGenerated by just build-runner; do not edit by hand.\n\n' +
  [...packages]
    .sort(([a], [b]) => a.localeCompare(b, 'en'))
    .map(([, text]) => text)
    .join('\n-----\n\n');
const artifacts = new Map([
  ['bin/stellar.mjs', result.outputFiles[0].text],
  ['THIRD_PARTY_NOTICES.txt', notices],
]);
for (const [path, content] of artifacts) {
  if (check) {
    const existing = await readFile(join(root, path), 'utf8').catch((error) => {
      if (error.code === 'ENOENT') return null;
      throw error;
    });
    if (existing !== content) {
      console.error(`${path} is stale or missing. Run just build-runner.`);
      process.exitCode = 1;
    }
  } else {
    await writeFile(join(root, path), content);
  }
}
if (!process.exitCode)
  console.log(
    check
      ? 'Runner bundle and notices are current.'
      : 'Runner bundle and notices generated.',
  );
