import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { errorCode, required } from './support/values.ts';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv[2] === '--check';
if (process.argv.length > 3 || (process.argv[2] && !check))
  throw new Error('Usage: node scripts/build-viewer.ts [--check]');
const result = await build({
  absWorkingDir: root,
  entryPoints: ['viewer/app.ts'],
  outfile: 'assets/viewer/app.js',
  bundle: true,
  platform: 'browser',
  format: 'iife',
  target: 'es2022',
  write: false,
  metafile: true,
  banner: {
    js: '// Generated by just build-viewer. Edit viewer/, then regenerate.',
  },
});
if (
  Object.values(result.metafile.outputs).some((output) => output.imports.length)
)
  throw new Error('The standalone viewer must have no external imports.');
const output = new URL('../assets/viewer/app.js', import.meta.url);
const content = required(result.outputFiles[0]).text;
if (check) {
  const previous = await readFile(output, 'utf8').catch((error: unknown) => {
    if (errorCode(error) === 'ENOENT') return null;
    throw error;
  });
  if (previous !== content) {
    console.error(
      'assets/viewer/app.js is stale or missing. Run just build-viewer.',
    );
    process.exitCode = 1;
  }
} else await writeFile(output, content);
if (!process.exitCode)
  console.log(check ? 'Viewer bundle is current.' : 'Viewer bundle generated.');
