import { record, string, required, errorCode } from './support/values.ts';
import { build } from 'esbuild';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { isBuiltin } from 'node:module';
import { runtimeFiles, manifestPath, sha256 } from '../lib/installation.ts';
import { version } from '../lib/version.ts';

const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv[2] === '--check';
if (process.argv.length > 3 || (process.argv[2] && !check)) {
  throw new Error('Usage: node scripts/build-runner.ts [--check]');
}

// Check the source tree independently of the doctor's fixed allowlist. New
// runtime resources must be deliberately added to that list before generation.
const discovered = ['bin/stellar.mjs'];
for (const [directory, pattern] of [
  ['schemas', /\.schema\.json$/],
  ['assets/viewer', /\.(html|css|js|svg)$/],
  ['assets/viewer/locales', /\.json$/],
] as const) {
  for (const name of (await readdir(join(root, directory))).sort()) {
    // Editor locks and OS metadata are not runtime inputs; skip before stat.
    if (name.startsWith('.') || !pattern.test(name)) continue;
    const path = `${directory}/${name}`;
    if (!(await stat(join(root, path))).isFile())
      throw new Error(`Runtime resource is not a regular file: ${path}`);
    discovered.push(path);
  }
}
const missing = discovered.filter((path) => !runtimeFiles.includes(path));
const unexpected = runtimeFiles.filter((path) => !discovered.includes(path));
const duplicates = runtimeFiles.filter(
  (path, index) => runtimeFiles.indexOf(path) !== index,
);
if (missing.length || unexpected.length || duplicates.length)
  throw new Error(
    [
      'Runtime resource inventory is out of date; no artifacts were generated.',
      `Missing from runtimeFiles: ${missing.join(', ') || 'none'}.`,
      `Unexpected or absent resources: ${unexpected.join(', ') || 'none'}.`,
      `Duplicate entries: ${duplicates.join(', ') || 'none'}.`,
      'Update the fixed runtimeFiles list in lib/installation.ts to match the runtime files, remove duplicate entries, or restore missing resources.',
    ].join('\n'),
  );

const result = await build({
  absWorkingDir: root,
  entryPoints: ['bin/stellar.ts'],
  outfile: 'bin/stellar.mjs',
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node24',
  write: false,
  metafile: true,
  legalComments: 'inline',
  plugins: [
    {
      name: 'stellar-product-version',
      setup(builder) {
        builder.onLoad({ filter: /[/\\]package\.json$/ }, ({ path }) => {
          if (path !== join(root, 'package.json')) return;
          // Leave dependency manifests alone; only the product JSON import is
          // narrowed. No second version value or generated source file is kept.
          return { contents: JSON.stringify({ version }), loader: 'json' };
        });
      },
    },
  ],
  banner: {
    js: '// Generated by just build-runner. Edit bin/stellar.ts and lib/, then regenerate.\n// Dependency license texts: ../THIRD_PARTY_NOTICES.txt',
  },
});

for (const output of Object.values(result.metafile.outputs)) {
  for (const dependency of output.imports) {
    if (dependency.external && !isBuiltin(dependency.path)) {
      throw new Error(
        `Installed runner has an external package: ${dependency.path}`,
      );
    }
  }
}

// Include the full license of every dependency that actually enters the bundle.
const packages = new Map<string, string>();
for (const input of Object.keys(result.metafile.inputs)) {
  if (!('/' + input).includes('/node_modules/')) continue;
  let at = dirname(resolve(root, input));
  while (at !== root) {
    let pkg: Record<string, unknown>;
    try {
      pkg = record(
        JSON.parse(await readFile(join(at, 'package.json'), 'utf8')),
      );
    } catch (error) {
      if (errorCode(error) !== 'ENOENT') throw error;
      at = dirname(at);
      continue;
    }
    const identity = `${string(pkg['name'])}@${string(pkg['version'])}`;
    if (!packages.has(identity)) {
      let license;
      for (const name of ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'license']) {
        try {
          license = await readFile(join(at, name), 'utf8');
          break;
        } catch (error) {
          if (errorCode(error) !== 'ENOENT') throw error;
        }
      }
      if (!license)
        throw new Error(`Missing license for ${string(pkg['name'])}`);
      packages.set(
        identity,
        `${identity} (${string(pkg['license'])})\n\n${license.trim()}\n`,
      );
    }
    break;
  }
}
const notices =
  'Third-party software included in bin/stellar.mjs\nGenerated by just build-runner; do not edit by hand.\n\n' +
  [...packages]
    .sort(([a], [b]) => a.localeCompare(b, 'en'))
    .map(([, text]) => text)
    .join('\n-----\n\n');
const artifacts = new Map([
  ['bin/stellar.mjs', required(result.outputFiles[0]).text],
  ['THIRD_PARTY_NOTICES.txt', notices],
]);
const files: Record<string, string> = {};
for (const path of runtimeFiles)
  files[path] = sha256(
    artifacts.get(path) ?? (await readFile(join(root, path))),
  );
artifacts.set(manifestPath, JSON.stringify({ version, files }, null, 2) + '\n');
for (const [path, content] of artifacts) {
  if (check) {
    const existing = await readFile(join(root, path), 'utf8').catch(
      (error: unknown) => {
        if (errorCode(error) === 'ENOENT') return null;
        throw error;
      },
    );
    if (existing !== content) {
      console.error(`${path} is stale or missing. Run just build-runner.`);
      process.exitCode = 1;
    }
  } else {
    await writeFile(join(root, path), content);
  }
}
if (!process.exitCode)
  console.log(
    check
      ? 'Runner bundle, integrity manifest, and notices are current.'
      : 'Runner bundle, integrity manifest, and notices generated.',
  );
